// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SSMS.Data;

#nullable disable

namespace SSMS.Migrations
{
    [DbContext(typeof(SSMSContext))]
    partial class SSMSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClassMaterial", b =>
                {
                    b.Property<int>("MaterialId")
                        .HasColumnType("int")
                        .HasColumnName("MaterialID");

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("ClassID");

                    b.HasKey("MaterialId", "ClassId")
                        .HasName("PK__ClassMat__D9B7816D0C48C695");

                    b.HasIndex("ClassId");

                    b.ToTable("ClassMaterials", (string)null);
                });

            modelBuilder.Entity("SSMS.Models.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("ClassID");

                    b.Property<string>("ClassNameArabic")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ClassNameEnglish")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ClassId")
                        .HasName("PK__Classes__CB1927A0B4B0C05C");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("SSMS.Models.Mark", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("ClassID");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int")
                        .HasColumnName("MaterialID");

                    b.Property<decimal>("Mark1")
                        .HasColumnType("numeric(18, 0)")
                        .HasColumnName("Mark");

                    b.HasKey("StudentId", "ClassId", "MaterialId")
                        .HasName("PK__Marks__38B1BE101BEA22C5");

                    b.HasIndex("ClassId");

                    b.HasIndex("MaterialId");

                    b.ToTable("Marks");
                });

            modelBuilder.Entity("SSMS.Models.Material", b =>
                {
                    b.Property<int>("MaterialId")
                        .HasColumnType("int")
                        .HasColumnName("MaterialID");

                    b.Property<string>("MaterialNameArabic")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaterialNameEnglish")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaterialId")
                        .HasName("PK__Material__C506131783370C7D");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("SSMS.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("ClassID");

                    b.Property<string>("FullNameArabic")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullNameEnglish")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("StudentId")
                        .HasName("PK__Students__32C52A797BEFCD0F");

                    b.HasIndex("ClassId");

                    b.HasIndex(new[] { "UserId" }, "UQ__Students__1788CCAD10129B91")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("SSMS.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("TeacherID");

                    b.Property<string>("FullNameArabic")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullNameEnglish")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int")
                        .HasColumnName("MaterialID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("TeacherId")
                        .HasName("PK__Teachers__EDF2594478F4A71C");

                    b.HasIndex("MaterialId")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "UQ__Teachers__1788CCADD8C65CBA")
                        .IsUnique();

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("SSMS.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CCACC0EC1719");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ClassMaterial", b =>
                {
                    b.HasOne("SSMS.Models.Class", null)
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ClassMate__Class__47DBAE45");

                    b.HasOne("SSMS.Models.Material", null)
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ClassMate__Mater__46E78A0C");
                });

            modelBuilder.Entity("SSMS.Models.Mark", b =>
                {
                    b.HasOne("SSMS.Models.Class", "Class")
                        .WithMany("Marks")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK__Marks__ClassID__5812160E");

                    b.HasOne("SSMS.Models.Material", "Material")
                        .WithMany("Marks")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Marks__MaterialI__59063A47");

                    b.HasOne("SSMS.Models.Student", "Student")
                        .WithMany("Marks")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Marks__StudentID__571DF1D5");

                    b.Navigation("Class");

                    b.Navigation("Material");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SSMS.Models.Student", b =>
                {
                    b.HasOne("SSMS.Models.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Students__ClassI__4316F928");

                    b.HasOne("SSMS.Models.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("SSMS.Models.Student", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Students__UserID__440B1D61");

                    b.Navigation("Class");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SSMS.Models.Teacher", b =>
                {
                    b.HasOne("SSMS.Models.Material", "Material")
                        .WithOne("Teacher")
                        .HasForeignKey("SSMS.Models.Teacher", "MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Teachers__Materi__3F466844");

                    b.HasOne("SSMS.Models.User", "User")
                        .WithOne("Teacher")
                        .HasForeignKey("SSMS.Models.Teacher", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Teachers__UserID__3E52440B");

                    b.Navigation("Material");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SSMS.Models.Class", b =>
                {
                    b.Navigation("Marks");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("SSMS.Models.Material", b =>
                {
                    b.Navigation("Marks");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SSMS.Models.Student", b =>
                {
                    b.Navigation("Marks");
                });

            modelBuilder.Entity("SSMS.Models.User", b =>
                {
                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });
#pragma warning restore 612, 618
        }
    }
}
